version: '3'

services:
  rabbitmq: 
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=gues
      - RABBITMQ_DEFAULT_PASS=gues